import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import './globals.css';
import '@radix-ui/themes/styles.css';
import './theme-config.css';
import { Theme } from '@radix-ui/themes';

//componentes
import Header from '../components/header';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Maya FC',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={rubik.className}>
				<Header />
				<Theme accentColor='amber'>{children}</Theme>
			</body>
		</html>
	);
}
